--- #YAML:1.0
name:                Acme-Terror-NL
version:             0.03
abstract:            Fetch the current NL terror alert level
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    constant:                      1.01
    LWP::Simple:                   0
    Test::Simple:                  0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - M. Blom (blom@cpan.org)
