--- #YAML:1.0
name:               Acme-Terror-NL
version:            0.04
abstract:           Fetch the current NL terror alert level
author:
    - M. Blom (blom@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    constant:      1.01
    LWP::Simple:   0
    Test::Simple:  0.44
resources:
    repository:  https://github.com/b10m/p5-Acme-Terror-NL
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
